[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'sainnhe/edge'

[[plugins]]
repo = 'endel/vim-github-colorscheme'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  source ~/dotfiles/nvim/plugins/lightline.rc.vim
'''

[[plugins]]
repo = "itchyny/vim-gitbranch"

[[plugins]]
repo = 'yasukotelin/shirotelin'
hook_add = '''
  " for preview bat
  let $BAT_THEME='GitHub'
  " for fzf color theme
  let $FZF_DEFAULT_OPTS="--color=light"
'''

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = "sgur/vim-textobj-parameter"

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = '!has("nvim")'

[[plugins]]
repo = 'roxma/nvim-yarp'
if = '!has("nvim")'

[[plugins]]
repo = 'lervag/vimtex'
hook_add = '''
  let g:vimtex_syntax_conceal_disable = 1
  let g:vimtex_quickfix_ignore_filters=["Package caption Warning"]
  let g:vimtex_compiler_latexmk = {
      \ 'options' : [
      \   '-shell-escape',
      \ ],
      \}
  if executable('SumatraPDF')
    let g:vimtex_view_general_viewer = 'SumatraPDF'
    let g:vimtex_view_general_options
        \ = '-reuse-instance -forward-search @tex @line @pdf'
  else
    let g:vimtex_view_method = 'zathura'
    let g:vimtex_view_general_options = "-x \"nvr +%{line} %{input}\" --synctex-forward @line:0:@tex @pdf"
  endif
'''

[[plugins]]
repo = 'machakann/vim-sandwich'

[[plugins]]
repo = 'lambdalisue/guise.vim'
hook_add = '''
  let g:guise_edit_opener='vsplit'
'''

[[plugins]]
repo = 'vim-denops/denops.vim'
hook_add = '''
  let g:denops_server_addr = '127.0.0.1:32123' 
'''

[[plugins]]
repo = "prabirshrestha/vim-lsp"
if = '!has("nvim")'
hook_add = '''
	let g:lsp_completion_documentation_enabled = 0
	let g:lsp_signature_help_enabled = 0
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
if = '!has("nvim")'

[[plugins]]
repo = 'hrsh7th/vim-vital-vs'

[[plugins]]
repo = 'statiolake/vim-quickrun-runner-nvimterm'
if = 'has("nvim")'

[[plugins]]
repo = 'RRethy/vim-illuminate'
lua_add = '''
require('illuminate').configure({
    delay = 800,
})
'''

[[plugins]]
repo = 'williamboman/mason.nvim'
lua_add = '''
  require('mason').setup()
'''

[[plugins]]
repo = "numToStr/Comment.nvim"
lua_add = '''
  require('Comment').setup()
'''

[[plugins]]
repo = "vim-denops/denops-shared-server.vim"

[[plugins]]
repo = "lambdalisue/fern-hijack.vim"
